[package]
name = "red-blox/red"
version = "2.0.0-rc.10"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = [
	"default.project.json",
	"lib",
	"lib/**",
	"LICENSE",
	"wally.toml",
	"README.md",
]

[dependencies]
Future = "red-blox/future@^1.0.0"
Clock = "red-blox/clock@^1.0.0"
Spawn = "red-blox/spawn@^1.0.0"
Guard = "red-blox/guard@^1.0.0"
